name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: check build name
      run: echo ${BUILD}
    - name: check remote build name
      run: echo ${BUILD_REMOTE}
    - name: Build the Docker image
      run: sudo docker build -t $BUILD:latest -t $BUILD_REMOTE:latest .

  push_local:
    runs-on: self-hosted
    needs: build
    steps:
    - name: check build name
      run: echo ${BUILD}:latest
    - name: Build the Docker image
      run: sudo docker push ${BUILD}:latest

  push_remote:
    runs-on: self-hosted
    needs: build
    steps:
    -   name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_TOKEN
    -   name: push to reomote
        run: sudo docker push $BUILD_REMOTE:latest

  
  notify:
    runs-on: self-hosted
    needs: [push_local, push_remote]
    steps:
      - name: notify with telegram
        run: >-
          curl -X POST -H 'Content-Type: application/json' -d '{"text":"[GHR]\ndeployed '${BUILD}'"}' https://service.outer-heaven.duckdns.org/telegram
  
  notify-error:
    runs-on: self-hosted
    needs: [pre, build, deploy]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: notify error
        run: >-
          curl -X POST -H 'Content-Type: application/json' -d '{"text":"[GHR]\nRROR in '${BUILD}'"}' https://service.outer-heaven.duckdns.org/telegram
